######################################################################
# Automatically generated by qmake (3.0) ?? 2? 19 17:50:06 2013
######################################################################

TEMPLATE = app
TARGET = graphcanvas
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += graphcanvas.h
SOURCES += main.cpp graphcanvas.cpp
